INFO 2017-03-31 16:24:31,484 ilastik_main 7621 140736734557120 Starting ilastik from "/Applications/ilastik-1.2.0-OSX.app/Contents/ilastik-release".
INFO 2017-03-31 16:24:36,533 vigraOperators 7621 140736734557120 Using fast filters.
INFO 2017-03-31 16:24:40,962 opThresholdTwoLevels 7621 140736734557120 Using 'vigra' labeling implemetation
WARNING 2017-03-31 16:24:41,305 opConservationTracking 7621 140736734557120 Could not find any ILP solver
WARNING 2017-03-31 16:24:41,565 __init__ 7621 140736734557120 Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: dlopen(/Applications/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/pgmlink.so, 2): Library not loaded: @rpath/libconcert.dylib
  Referenced from: /Applications/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/pgmlink.so
  Reason: image not found
INFO 2017-11-02 13:36:03,040 ilastik_main 1723 140736802685888 Starting ilastik from "/Applications/ilastik-1.2.0-OSX.app/Contents/ilastik-release".
INFO 2017-11-02 13:36:18,217 vigraOperators 1723 140736802685888 Using fast filters.
INFO 2017-11-02 13:36:53,144 opThresholdTwoLevels 1723 140736802685888 Using 'vigra' labeling implemetation
WARNING 2017-11-02 13:36:56,853 opConservationTracking 1723 140736802685888 Could not find any ILP solver
WARNING 2017-11-02 13:36:56,965 __init__ 1723 140736802685888 Failed to import structured learning tracking workflow. For this workflow, see the installationinstructions on our website ilastik.org; check dependencies: dlopen(/Applications/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/pgmlink.so, 2): Library not loaded: @rpath/libconcert.dylib
  Referenced from: /Applications/ilastik-1.2.0-OSX.app/Contents/Resources/lib/python2.7/site-packages/pgmlink.so
  Reason: image not found
WARNING 2019-03-21 14:37:42,122 warnings 4812 4549850560 loggingHelpers.py(76): ResourceWarning: unclosed file <_io.TextIOWrapper name='/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/ilastik_logging/logging_config.json' mode='r' encoding='US-ASCII'>
INFO 2019-03-21 14:37:42,128 ilastik_main 4812 4549850560 Starting ilastik from "/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release".
INFO 2019-03-21 14:37:43,684 vigraOperators 4812 4549850560 Using fast filters.
WARNING 2019-03-21 14:37:43,725 warnings 4812 4549850560 _bootstrap.py(219): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
WARNING 2019-03-21 14:37:43,732 warnings 4812 4549850560 _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING 2019-03-21 14:37:43,754 warnings 4812 4549850560 _bootstrap.py(219): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
WARNING 2019-03-21 14:37:43,782 warnings 4812 4549850560 _bootstrap.py(219): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
WARNING 2019-03-21 14:37:43,825 warnings 4812 4549850560 _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING 2019-03-21 14:37:43,911 warnings 4812 4549850560 _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING 2019-03-21 14:37:44,566 warnings 4812 4549850560 _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING 2019-03-21 14:37:44,591 warnings 4812 4549850560 _bootstrap.py(219): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
WARNING 2019-03-21 14:37:44,785 warnings 4812 4549850560 cross_validation.py(41): DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
WARNING 2019-03-21 14:37:44,857 warnings 4812 4549850560 _bootstrap.py(219): ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
WARNING 2019-03-21 14:37:44,871 warnings 4812 4549850560 _bootstrap.py(219): RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
WARNING 2019-03-21 14:37:44,991 opConservationTracking 4812 4549850560 Could not find any ILP solver
WARNING 2019-03-21 14:37:45,000 opStructuredTracking 4812 4549850560 Could not find any ILP solver
WARNING 2019-03-21 14:37:45,004 structuredTrackingWorkflow 4812 4549850560 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
WARNING 2019-03-21 14:37:52,133 warnings 4812 123145423360000 loggingHelpers.py(76): ResourceWarning: unclosed file <_io.TextIOWrapper name='/Applications/ilastik-1.3.0-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/ilastik_logging/logging_config.json' mode='r' encoding='US-ASCII'>
INFO 2019-03-21 14:46:40,995 ilastik_main 5160 4424558016 Starting ilastik from "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release".
INFO 2019-03-21 14:46:42,341 filterOperators 5160 4424558016 Using fast filters.
WARNING 2019-03-21 14:46:42,346 warnings 5160 4424558016 __init__.py(11): UserWarning: init: Could not import tiktorch classifier
ERROR 2019-03-21 14:46:43,696 PluginManager 5160 4424558016 Unable to import plugin: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_contours_with_head_export
Traceback (most recent call last):
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_contours_with_head_export.py", line 10, in <module>
    from skimage import measure
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/__init__.py", line 177, in <module>
    from .data import data_dir
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/data/__init__.py", line 15, in <module>
    from ..io import imread, use_plugin
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/collection.py", line 12, in <module>
    from PIL import Image
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: dlopen(/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Reason: Incompatible library version: _imaging.cpython-36m-darwin.so requires version 13.0.0 or later, but libjpeg.9.dylib provides version 12.0.0
ERROR 2019-03-21 14:46:43,708 PluginManager 5160 4424558016 Unable to import plugin: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_contour_export
Traceback (most recent call last):
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_contour_export.py", line 10, in <module>
    from skimage import measure
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/__init__.py", line 177, in <module>
    from .data import data_dir
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/data/__init__.py", line 15, in <module>
    from ..io import imread, use_plugin
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/collection.py", line 12, in <module>
    from PIL import Image
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: dlopen(/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Reason: Incompatible library version: _imaging.cpython-36m-darwin.so requires version 13.0.0 or later, but libjpeg.9.dylib provides version 12.0.0
ERROR 2019-03-21 14:46:43,713 PluginManager 5160 4424558016 Unable to import plugin: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_mwt_export
Traceback (most recent call last):
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_mwt_export.py", line 12, in <module>
    from skimage import measure
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/__init__.py", line 177, in <module>
    from .data import data_dir
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/data/__init__.py", line 15, in <module>
    from ..io import imread, use_plugin
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/collection.py", line 12, in <module>
    from PIL import Image
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: dlopen(/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Reason: Incompatible library version: _imaging.cpython-36m-darwin.so requires version 13.0.0 or later, but libjpeg.9.dylib provides version 12.0.0
ERROR 2019-03-21 14:46:43,719 PluginManager 5160 4424558016 Unable to import plugin: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_ctc_export
Traceback (most recent call last):
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/plugins_default/tracking_ctc_export.py", line 4, in <module>
    from skimage.external import tifffile
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/__init__.py", line 177, in <module>
    from .data import data_dir
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/data/__init__.py", line 15, in <module>
    from ..io import imread, use_plugin
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/skimage/io/collection.py", line 12, in <module>
    from PIL import Image
  File "/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: dlopen(/private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /private/var/folders/d0/d5jy1zbd3h36bkzhnsd9snyw0000gr/T/AppTranslocation/53A0523A-4C3A-490F-A295-540856D4BDF5/d/ilastik-1.3.2post1-OSX.app/Contents/Resources/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Reason: Incompatible library version: _imaging.cpython-36m-darwin.so requires version 13.0.0 or later, but libjpeg.9.dylib provides version 12.0.0
WARNING 2019-03-21 14:46:43,776 opConservationTracking 5160 4424558016 Could not find any ILP solver
WARNING 2019-03-21 14:46:43,786 opStructuredTracking 5160 4424558016 Could not find any ILP solver
WARNING 2019-03-21 14:46:43,789 structuredTrackingWorkflow 5160 4424558016 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
